name: R Bindings

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-r:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, any::jsonlite
          needs: check
          working-directory: bindings/r

      - name: Enable MSVC Dev Cmd (Windows)
        if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0

      - name: Build QwD Shared Library (ReleaseFast)
        if: matrix.os != 'windows-latest'
        run: zig build -Doptimize=ReleaseFast

      - name: Build QwD Shared Library Windows (ReleaseFast)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: zig build -Doptimize=ReleaseFast -Dtarget=x86_64-windows-gnu

      - name: Run R Tests
        uses: r-lib/actions/check-r-package@v2
        with:
          working-directory: bindings/r
          error-on: '"error"'
